os:
 - linux
 - osx
language: csharp
mono: none
sudo: required
dist: xenial
dotnet: 2.2.104
script:
 - dotnet restore
after_success:
 - dotnet publish -c Release
 - sh AppDir/bundle.sh
deploy:
  provider: releases
  api_key: $GITHUBOAUTH
  file:
   - strans-linux.AppImage
   - bin/Release/netcoreapp2.2/strans.dll
  skip_cleanup: true
  draft: true
  on:
    tags: false